/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.text.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author Dharmvir kumar
 */

public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
    }


public final class LengthRestrictedDocument extends PlainDocument {

  private final int limit;

  public LengthRestrictedDocument(int limit) {
    this.limit = limit;
  }

  @Override
  public void insertString(int offs, String str, AttributeSet a)
      throws BadLocationException {
    if (str == null)
      return;

    if ((getLength() + str.length()) <= limit) {
      super.insertString(offs, str, a);
    }
  }
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EId = new javax.swing.JTextField();
        Uname = new javax.swing.JLabel();
        Uname1 = new javax.swing.JLabel();
        Esalary = new javax.swing.JTextField();
        Uname2 = new javax.swing.JLabel();
        Ephone = new javax.swing.JTextField();
        Uname3 = new javax.swing.JLabel();
        EAddhar = new javax.swing.JTextField();
        Uname4 = new javax.swing.JLabel();
        Uname5 = new javax.swing.JLabel();
        Eage = new javax.swing.JTextField();
        Uname6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Eaddress = new javax.swing.JTextArea();
        SubmitDeatail = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Ename = new javax.swing.JTextField();
        Uname7 = new javax.swing.JLabel();
        Edes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD EMPLOYEE DETAIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        EId.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        EId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIdActionPerformed(evt);
            }
        });

        Uname.setBackground(new java.awt.Color(255, 255, 255));
        Uname.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname.setForeground(new java.awt.Color(153, 153, 153));
        Uname.setText("Enter Employee ID :");

        Uname1.setBackground(new java.awt.Color(255, 255, 255));
        Uname1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname1.setForeground(new java.awt.Color(153, 153, 153));
        Uname1.setText("Enter Designation :");

        Esalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Esalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsalaryActionPerformed(evt);
            }
        });

        Uname2.setBackground(new java.awt.Color(255, 255, 255));
        Uname2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname2.setForeground(new java.awt.Color(153, 153, 153));
        Uname2.setText("Enter Salary:");

        Ephone.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Ephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EphoneActionPerformed(evt);
            }
        });

        Uname3.setBackground(new java.awt.Color(255, 255, 255));
        Uname3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname3.setForeground(new java.awt.Color(153, 153, 153));
        Uname3.setText("Enter Phone :");

        EAddhar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        EAddhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EAddharActionPerformed(evt);
            }
        });

        Uname4.setBackground(new java.awt.Color(255, 255, 255));
        Uname4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname4.setForeground(new java.awt.Color(153, 153, 153));
        Uname4.setText("Enter Addhar No :");

        Uname5.setBackground(new java.awt.Color(255, 255, 255));
        Uname5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname5.setForeground(new java.awt.Color(153, 153, 153));
        Uname5.setText("Enter Address:");

        Eage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Eage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EageActionPerformed(evt);
            }
        });

        Uname6.setBackground(new java.awt.Color(255, 255, 255));
        Uname6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname6.setForeground(new java.awt.Color(153, 153, 153));
        Uname6.setText("Enter Age :");

        Eaddress.setColumns(20);
        Eaddress.setRows(5);
        Eaddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(153, 153, 153)));
        jScrollPane1.setViewportView(Eaddress);

        SubmitDeatail.setBackground(new java.awt.Color(0, 204, 204));
        SubmitDeatail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitDeatail.setForeground(new java.awt.Color(102, 102, 102));
        SubmitDeatail.setText("SUBMIT DETAILS");
        SubmitDeatail.setBorderPainted(false);
        SubmitDeatail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitDeatail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitDeatailMouseClicked(evt);
            }
        });
        SubmitDeatail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDeatailActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(0, 204, 204));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(102, 102, 102));
        Back.setText("BACK");
        Back.setBorderPainted(false);
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Ename.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnameActionPerformed(evt);
            }
        });

        Uname7.setBackground(new java.awt.Color(255, 255, 255));
        Uname7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname7.setForeground(new java.awt.Color(153, 153, 153));
        Uname7.setText("Enter Employee Name :");

        Edes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Edes.setForeground(new java.awt.Color(102, 102, 102));
        Edes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Junior Software Developer", "Senior Software Developer", "UX/UI Designer", "Data Base Manager" }));
        Edes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitDeatail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EId, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Eage, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Uname6, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Esalary, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Uname2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EAddhar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Uname4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ename, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Uname7, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Uname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ephone)
                    .addComponent(Uname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Uname5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(Edes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Uname1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Uname3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Uname5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Uname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Uname7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ename, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Uname2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Esalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Uname4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EAddhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Uname6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitDeatail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(672, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EIdActionPerformed

    private void EsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EsalaryActionPerformed

    private void EphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EphoneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EphoneActionPerformed

    private void EAddharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EAddharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EAddharActionPerformed

    private void EageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EageActionPerformed

    private void SubmitDeatailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDeatailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitDeatailActionPerformed

    private void SubmitDeatailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitDeatailMouseClicked
        // TODO add your handling code here:
        
        
        String PATTERN = "^[0-9]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(EId.getText());
        
        if(!match.matches())
        {
            JOptionPane.showMessageDialog(null, "you can enter only numbers in Employee ID","Incorrect Format error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        String PATTERN1 = "^[a-zA-Z]{0,20}$";
        Pattern patt1 = Pattern.compile(PATTERN1);
        Matcher match1 = patt1.matcher(Ename.getText());
        
        if(!match1.matches()){
            JOptionPane.showMessageDialog(null, "you can enter only letters in name","Incorrect Format error",JOptionPane.ERROR_MESSAGE);
                }    
        else{
        String PATTERN2 = "^[0-9]{0,20}$";
        Pattern patt2 = Pattern.compile(PATTERN2);
        Matcher match2 = patt2.matcher(Esalary.getText());
        
        if(!match2.matches()){
            JOptionPane.showMessageDialog(null, "you can enter only numbers in salary","Incorrect Format error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        String PATTERN3 = "^[0-9]{0,20}$";
        Pattern patt3 = Pattern.compile(PATTERN3);
        Matcher match3 = patt3.matcher(EAddhar.getText());
        
        if(!match3.matches()){
            JOptionPane.showMessageDialog(null, "you can enter only numbers in Addhar","Incorrect Format error",JOptionPane.ERROR_MESSAGE);
                }
        else{
        String PATTERN4 = "^[a-z]{0,40}$";
        Pattern patt4 = Pattern.compile(PATTERN4);
        Matcher match4 = patt4.matcher(Eaddress.getText());
        
        if(!match4.matches()){
            JOptionPane.showMessageDialog(null, "you can only enter numbers and letters in Address","Incorrect Format error",JOptionPane.ERROR_MESSAGE);
                }
        else{
        String PATTERN5 = "^[0-9]{0,20}$";
        Pattern patt5 = Pattern.compile(PATTERN5);
        Matcher match5 = patt5.matcher(Ephone.getText());
        
        if(!match5.matches()){
            JOptionPane.showMessageDialog(null, "you can enter only numbers in Phone","Incorrect Format error",JOptionPane.ERROR_MESSAGE);
                }
        else{
        String PATTERN6 = "^[0-9]{0,20}$";
        Pattern patt6 = Pattern.compile(PATTERN6);
        Matcher match6 = patt6.matcher(Eage.getText());
        
        if(!match6.matches()){
            JOptionPane.showMessageDialog(null, "you can enter only numbers in age","Incorrect Format error",JOptionPane.ERROR_MESSAGE);
                }
        else{
                
        try{
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db","root","")) {
                String sql = "insert into `empdetail` (EmpId, EmpName, EmpDesignation, EmpSalary, EmpPhone, EmpAddhar, EmpAddress, EmpAge) values (?,?,?,?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, EId.getText());
                pst.setString(2, Ename.getText());
                pst.setString(3, Edes.getSelectedItem().toString());
                pst.setString(4, Esalary.getText());
                pst.setString(5, Ephone.getText());
                pst.setString(6, EAddhar.getText());
                pst.setString(7, Eaddress.getText());
                pst.setString(8, Eage.getText());
                
                pst.execute();
                
                String sql2 = "insert into `salary` (EmpId, BasicSalary) values (?, ?)";
                PreparedStatement pst2 = con.prepareStatement(sql2);
                pst2.setString(1, EId.getText());
                pst2.setString(2, Esalary.getText());
                
                pst2.execute();
                JOptionPane.showMessageDialog(null,"Data Succesfully Inserted");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
              }
            }
           }
          }
         }
        }
       }
     }
    }//GEN-LAST:event_SubmitDeatailMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        MainMenu m = new MainMenu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void EnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnameActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField EAddhar;
    private javax.swing.JTextField EId;
    private javax.swing.JTextArea Eaddress;
    private javax.swing.JTextField Eage;
    private javax.swing.JComboBox<String> Edes;
    private javax.swing.JTextField Ename;
    private javax.swing.JTextField Ephone;
    private javax.swing.JTextField Esalary;
    private javax.swing.JButton SubmitDeatail;
    private javax.swing.JLabel Uname;
    private javax.swing.JLabel Uname1;
    private javax.swing.JLabel Uname2;
    private javax.swing.JLabel Uname3;
    private javax.swing.JLabel Uname4;
    private javax.swing.JLabel Uname5;
    private javax.swing.JLabel Uname6;
    private javax.swing.JLabel Uname7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
