/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import com.sun.glass.events.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
/**
 *
 * @author Dharmvir kumar
 */
public class DeleteUser extends javax.swing.JFrame {

    /**
     * Creates new form UpdateUser
     */
    public DeleteUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubmitDeatail = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Uname3 = new javax.swing.JLabel();
        EAddhar = new javax.swing.JTextField();
        Ename = new javax.swing.JTextField();
        Uname4 = new javax.swing.JLabel();
        Uname7 = new javax.swing.JLabel();
        Uname5 = new javax.swing.JLabel();
        EId = new javax.swing.JTextField();
        Eage = new javax.swing.JTextField();
        Uname = new javax.swing.JLabel();
        Uname6 = new javax.swing.JLabel();
        Uname1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Eaddress = new javax.swing.JTextArea();
        Edes = new javax.swing.JTextField();
        Esalary = new javax.swing.JTextField();
        Uname2 = new javax.swing.JLabel();
        Ephone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubmitDeatail.setBackground(new java.awt.Color(0, 204, 204));
        SubmitDeatail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitDeatail.setForeground(new java.awt.Color(102, 102, 102));
        SubmitDeatail.setText("DELETE DETAILS");
        SubmitDeatail.setBorderPainted(false);
        SubmitDeatail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitDeatail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitDeatailMouseClicked(evt);
            }
        });
        SubmitDeatail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDeatailActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(0, 204, 204));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(102, 102, 102));
        Back.setText("BACK");
        Back.setBorderPainted(false);
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DELETE EMPLOYEE DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        Uname3.setBackground(new java.awt.Color(255, 255, 255));
        Uname3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname3.setForeground(new java.awt.Color(153, 153, 153));
        Uname3.setText("Enter Phone :");

        EAddhar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        EAddhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EAddharActionPerformed(evt);
            }
        });

        Ename.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnameActionPerformed(evt);
            }
        });

        Uname4.setBackground(new java.awt.Color(255, 255, 255));
        Uname4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname4.setForeground(new java.awt.Color(153, 153, 153));
        Uname4.setText("Enter Addhar No :");

        Uname7.setBackground(new java.awt.Color(255, 255, 255));
        Uname7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname7.setForeground(new java.awt.Color(153, 153, 153));
        Uname7.setText("Enter Employee Name :");

        Uname5.setBackground(new java.awt.Color(255, 255, 255));
        Uname5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname5.setForeground(new java.awt.Color(153, 153, 153));
        Uname5.setText("Enter Address:");

        EId.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        EId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIdActionPerformed(evt);
            }
        });
        EId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EIdKeyPressed(evt);
            }
        });

        Eage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Eage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EageActionPerformed(evt);
            }
        });

        Uname.setBackground(new java.awt.Color(255, 255, 255));
        Uname.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname.setForeground(new java.awt.Color(153, 153, 153));
        Uname.setText("Enter Employee ID :");

        Uname6.setBackground(new java.awt.Color(255, 255, 255));
        Uname6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname6.setForeground(new java.awt.Color(153, 153, 153));
        Uname6.setText("Enter Age :");

        Uname1.setBackground(new java.awt.Color(255, 255, 255));
        Uname1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname1.setForeground(new java.awt.Color(153, 153, 153));
        Uname1.setText("Enter Designation :");

        Eaddress.setColumns(20);
        Eaddress.setRows(5);
        Eaddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(153, 153, 153)));
        jScrollPane1.setViewportView(Eaddress);

        Edes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Edes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdesActionPerformed(evt);
            }
        });

        Esalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Esalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsalaryActionPerformed(evt);
            }
        });

        Uname2.setBackground(new java.awt.Color(255, 255, 255));
        Uname2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Uname2.setForeground(new java.awt.Color(153, 153, 153));
        Uname2.setText("Enter Salary:");

        Ephone.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(153, 153, 153)));
        Ephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EphoneActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("*NOTE : PRESS ENTER KEY TO VIEW EMPLOYE DETAILS AFTER WRITING EMPTOYEE ID.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitDeatail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EId, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Eage, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Uname6, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Esalary, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Uname2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EAddhar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Uname4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ename, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Uname7, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Edes)
                                .addComponent(Ephone)
                                .addComponent(Uname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Uname5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Uname1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Uname)
                    .addComponent(Uname1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Uname7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ename, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Uname2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Esalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Uname4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EAddhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Edes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Uname3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(Uname5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Uname6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitDeatail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitDeatailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitDeatailMouseClicked
        // TODO add your handling code here:
        String v1 = EId.getText();
        int p = JOptionPane.showConfirmDialog(null,"Are You Sure to Delete Data ?", "Delete Record", JOptionPane.YES_NO_OPTION);
        if (p == 0){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db","root","");
            String sql = "DELETE FROM empdetail WHERE EmpId = '"+v1+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            
            String sql2 = "DELETE FROM salary WHERE EmpId = '"+v1+"'";
            PreparedStatement pst2 = con.prepareStatement(sql2);
            pst2.execute();
            
            JOptionPane.showMessageDialog(null,"Data Deleted Succesfully");
           
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_SubmitDeatailMouseClicked

    private void SubmitDeatailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDeatailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitDeatailActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        MainMenu m = new MainMenu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void EAddharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EAddharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EAddharActionPerformed

    private void EnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnameActionPerformed

    private void EIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EIdActionPerformed

    private void EageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EageActionPerformed

    private void EdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdesActionPerformed

    private void EsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EsalaryActionPerformed

    private void EphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EphoneActionPerformed

    private void EIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EIdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db","root","");
            String sql = "select * from empdetail where EmpId = ?";
            ResultSet rs = null;
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, EId.getText());
            rs = pst.executeQuery();
        if (rs.next())
            {
            Ename.setText(rs.getString(2));
            Edes.setText(rs.getString(3));
            Esalary.setText(rs.getString(4));
            Ephone.setText(rs.getString(5));
            EAddhar.setText(rs.getString(6));
            Eaddress.setText(rs.getString(7));
            Eage.setText(rs.getString(8));
            }
                }
            
            
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
    }//GEN-LAST:event_EIdKeyPressed
        }
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField EAddhar;
    private javax.swing.JTextField EId;
    private javax.swing.JTextArea Eaddress;
    private javax.swing.JTextField Eage;
    private javax.swing.JTextField Edes;
    private javax.swing.JTextField Ename;
    private javax.swing.JTextField Ephone;
    private javax.swing.JTextField Esalary;
    private javax.swing.JButton SubmitDeatail;
    private javax.swing.JLabel Uname;
    private javax.swing.JLabel Uname1;
    private javax.swing.JLabel Uname2;
    private javax.swing.JLabel Uname3;
    private javax.swing.JLabel Uname4;
    private javax.swing.JLabel Uname5;
    private javax.swing.JLabel Uname6;
    private javax.swing.JLabel Uname7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
